In [1]:
import pandas as pd

## DATA LOADING & OVERVIEW

### 1. Load the dataset

In [4]:
df = pd.read_csv("playstore_dataset.csv")

### 2. Display the first 5 rows

In [5]:
print(df.head())

                                                 App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1
1                                Coloring book moana  ART_AND_DESIGN     3.9
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone
1     967   14M     500,000+  Free     0       Everyone
2   87510  8.7M   5,000,000+  Free     0       Everyone
3  215644   25M  50,000,000+  Free     0           Teen
4     967  2.8M     100,000+  Free     0       Everyone

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0
1  Art & Design;Pretend Play  January 15, 2018               2.0.0
2               Art & Design    August 1, 2018               1.2.4
3               Art & Design      June 8, 2018  Varies with device
4    Art & Design;Creativity     June 20, 2018                 1.1

    Android Ver
0  4.0.3 and up
1  4.0.3 and up
2  4.0.3 and up
3    4.2 and up
4    4.4 and up

### 3. Display the last 5 rows

In [6]:
print(df.tail())

                                                 App             Category  \
10836                               Sya9a Maroc - FR               FAMILY
10837               Fr. Mike Schmitz Audio Teachings               FAMILY
10838                         Parkinson Exercices FR              MEDICAL
10839                  The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE
10840  iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE

       Rating Reviews                Size     Installs  Type Price  \
10836     4.5      38                 53M       5,000+  Free     0
10837     5.0       4                3.6M         100+  Free     0
10838     NaN       3                9.5M       1,000+  Free     0
10839     4.5     114  Varies with device       1,000+  Free     0
10840     4.5  398307                 19M  10,000,000+  Free     0

      Content Rating             Genres      Last Updated         Current Ver  \
10836       Everyone          Education     July 25, 2017                1.48
10837       Everyone          Education      July 6, 2018                 1.0
10838       Everyone            Medical  January 20, 2017                 1.0
10839     Mature 17+  Books & Reference  January 19, 2015  Varies with device
10840       Everyone          Lifestyle     July 25, 2018  Varies with device

              Android Ver
10836          4.1 and up
10837          4.1 and up
10838          2.2 and up
10839  Varies with device
10840  Varies with device

### 4. Check dataset structure and non-null counts

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 2.2 MB

### 5. Generate summary statistics for all columns

In [8]:
print(df.describe(include="all"))

           App Category       Rating Reviews                Size    Installs  \
count    10841    10841  9367.000000   10841               10841       10841
unique    9660       34          NaN    6002                 462          22
top     ROBLOX   FAMILY          NaN       0  Varies with device  1,000,000+
freq         9     1972          NaN     596                1695        1579
mean       NaN      NaN     4.193338     NaN                 NaN         NaN
std        NaN      NaN     0.537431     NaN                 NaN         NaN
min        NaN      NaN     1.000000     NaN                 NaN         NaN
25%        NaN      NaN     4.000000     NaN                 NaN         NaN
50%        NaN      NaN     4.300000     NaN                 NaN         NaN
75%        NaN      NaN     4.500000     NaN                 NaN         NaN
max        NaN      NaN    19.000000     NaN                 NaN         NaN

         Type  Price Content Rating Genres    Last Updated  \
count   10840  10841          10840  10841           10841
unique      3     93              6    120            1378
top      Free      0       Everyone  Tools  August 3, 2018
freq    10039  10040           8714    842             326
mean      NaN    NaN            NaN    NaN             NaN
std       NaN    NaN            NaN    NaN             NaN
min       NaN    NaN            NaN    NaN             NaN
25%       NaN    NaN            NaN    NaN             NaN
50%       NaN    NaN            NaN    NaN             NaN
75%       NaN    NaN            NaN    NaN             NaN
max       NaN    NaN            NaN    NaN             NaN

               Current Ver Android Ver
count                10833       10838
unique                2832          33
top     Varies with device  4.1 and up
freq                  1459        2451
mean                   NaN         NaN
std                    NaN         NaN
min                    NaN         NaN
25%                    NaN         NaN
50%                    NaN         NaN
75%                    NaN         NaN
max                    NaN         NaN

### 6. Display all column names and their data types

In [9]:
print(df.dtypes)

App                   str
Category              str
Rating            float64
Reviews               str
Size                  str
Installs              str
Type                  str
Price                 str
Content Rating        str
Genres                str
Last Updated          str
Current Ver           str
Android Ver           str
dtype: object

## DATA CLEANING (REAL-WORLD SCENARIOS)

7.Identify missing values in each column

In [10]:
print(df.isnull().sum())

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

8.Remove rows where "Rating" is missing

In [12]:
df = df.dropna(subset=["Rating"])

9.Fill missing values in "Type" with the most frequent value (mode)

In [13]:
df["Type"] = df["Type"].fillna(df["Type"].mode()[0])

10.Remove duplicate records from the dataset

In [14]:
df = df.drop_duplicates()

11.Clean "Installs" (remove '+', ',' and non-numeric entries if present, convert to int)

In [40]:
df["Installs"] = df["Installs"].astype(int)
print(df["Installs"].head())

0       10000
1      500000
2     5000000
3    50000000
4      100000
Name: Installs, dtype: int64

12.Clean "Price" (remove '$' and convert to float)

In [41]:
df = df[df["Price"] != "Everyone"]
df["Price"] = df["Price"].astype(float)
print(df["Price"].head())

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Price, dtype: float64

13.Convert "Reviews" column to integer type

In [35]:
df["Reviews"] = df["Reviews"].fillna(0).astype(int)

14.Convert "Last Updated" column to datetime format

In [36]:
df["Last Updated"] = pd.to_datetime(df["Last Updated"])
print(df["Last Updated"].head())

0   2018-01-07
1   2018-01-15
2   2018-08-01
3   2018-06-08
4   2018-06-20
Name: Last Updated, dtype: datetime64[us]

## 3. STRING OPERATIONS

15.Convert all app names to lowercase

In [43]:
df["App"] = df["App"].str.lower()
print(df["App"].head())

0       photo editor & candy camera & grid & scrapbook
1                                  coloring book moana
2    u launcher lite – free live cool themes, hide ...
3                                sketch - draw & paint
4                pixel draw - number art coloring book
Name: App, dtype: str

16.Convert category names to uppercase

In [44]:
df["Category"] = df["Category"].str.upper()
print(df["Category"].head())

0    ART_AND_DESIGN
1    ART_AND_DESIGN
2    ART_AND_DESIGN
3    ART_AND_DESIGN
4    ART_AND_DESIGN
Name: Category, dtype: str

17.Split the "Genres" column into multiple parts (takes the first genre)

In [45]:
df["Primary_Genre"] = df["Genres"].str.split(";").str[0]
print(df[["Primary_Genre"]].head())

  Primary_Genre
0  Art & Design
1  Art & Design
2  Art & Design
3  Art & Design
4  Art & Design

18.Replace unwanted text patterns in "Category" (e.g., replacing underscores with spaces)

In [46]:
df["Category"] = df["Category"].str.replace("_", " ")
df.Category

0             ART AND DESIGN
1             ART AND DESIGN
2             ART AND DESIGN
3             ART AND DESIGN
4             ART AND DESIGN
                ...
10834                 FAMILY
10836                 FAMILY
10837                 FAMILY
10839    BOOKS AND REFERENCE
10840              LIFESTYLE
Name: Category, Length: 8892, dtype: str

In [47]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Primary_Genre
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,Art & Design
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,Art & Design
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,Art & Design
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,Art & Design
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,Art & Design
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,fr calculator,FAMILY,4.0,7,2.6M,500,Free,0.0,Everyone,Education,2017-06-18,1.0.0,4.1 and up,Education
10836,sya9a maroc - fr,FAMILY,4.5,38,53M,5000,Free,0.0,Everyone,Education,2017-07-25,1.48,4.1 and up,Education
10837,fr. mike schmitz audio teachings,FAMILY,5.0,4,3.6M,100,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up,Education
10839,the scp foundation db fr nn5n,BOOKS AND REFERENCE,4.5,114,Varies with device,1000,Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,Books & Reference
10840,ihoroscope - 2018 daily horoscope & astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,Lifestyle

### 4. FILTERING & SELECTION

19.Filter apps with rating greater than 4.5

In [50]:
highly_rating = df[df["Rating"] > 4.5]
print(highly_rating)

                                                     App             Category  \
2      u launcher lite – free live cool themes, hide ...       ART AND DESIGN
9                          kids paint free - drawing fun       ART AND DESIGN
13                                 mandala coloring book       ART AND DESIGN
16          photo designer - write your name with shapes       ART AND DESIGN
19                                          ibis paint x       ART AND DESIGN
...                                                  ...                  ...
10810                                  fr lupupa sermons             BUSINESS
10820                                    fr. daoud lamei               FAMILY
10829                     bulgarian french dictionary fr  BOOKS AND REFERENCE
10833                                        chemin (fr)  BOOKS AND REFERENCE
10837                   fr. mike schmitz audio teachings               FAMILY

       Rating  Reviews  Size  Installs  Type  Price Content Rating  \
2         4.7    87510  8.7M   5000000  Free    0.0       Everyone
9         4.7      121  3.1M     10000  Free    0.0       Everyone
13        4.6     4326   21M    100000  Free    0.0       Everyone
16        4.7     3632  5.5M    500000  Free    0.0       Everyone
19        4.6   224399   31M  10000000  Free    0.0       Everyone
...       ...      ...   ...       ...   ...    ...            ...
10810     4.8       19   21M       100  Free    0.0       Everyone
10820     5.0       22  8.6M      1000  Free    0.0           Teen
10829     4.6      603  7.4M     10000  Free    0.0       Everyone
10833     4.8       44  619k      1000  Free    0.0       Everyone
10837     5.0        4  3.6M       100  Free    0.0       Everyone

                        Genres Last Updated Current Ver   Android Ver  \
2                 Art & Design   2018-08-01       1.2.4  4.0.3 and up
9      Art & Design;Creativity   2018-07-03         2.8  4.0.3 and up
13                Art & Design   2018-06-26       1.0.4    4.4 and up
16                Art & Design   2018-07-31         3.1    4.1 and up
19                Art & Design   2018-07-30       5.5.4    4.1 and up
...                        ...          ...         ...           ...
10810                 Business   2018-06-12         1.0    4.4 and up
10820                Education   2018-06-27       3.8.0    4.1 and up
10829        Books & Reference   2016-06-19        2.96    4.1 and up
10833        Books & Reference   2014-03-23         0.8    2.2 and up
10837                Education   2018-07-06         1.0    4.1 and up

           Primary_Genre
2           Art & Design
9           Art & Design
13          Art & Design
16          Art & Design
19          Art & Design
...                  ...
10810           Business
10820          Education
10829  Books & Reference
10833  Books & Reference
10837          Education

[1838 rows x 14 columns]

20.Find all free apps

In [51]:
free_apps = df[df["Price"] == 0]
print(free_apps)

                                                     App             Category  \
0         photo editor & candy camera & grid & scrapbook       ART AND DESIGN
1                                    coloring book moana       ART AND DESIGN
2      u launcher lite – free live cool themes, hide ...       ART AND DESIGN
3                                  sketch - draw & paint       ART AND DESIGN
4                  pixel draw - number art coloring book       ART AND DESIGN
...                                                  ...                  ...
10834                                      fr calculator               FAMILY
10836                                   sya9a maroc - fr               FAMILY
10837                   fr. mike schmitz audio teachings               FAMILY
10839                      the scp foundation db fr nn5n  BOOKS AND REFERENCE
10840      ihoroscope - 2018 daily horoscope & astrology            LIFESTYLE

       Rating  Reviews                Size  Installs  Type  Price  \
0         4.1      159                 19M     10000  Free    0.0
1         3.9      967                 14M    500000  Free    0.0
2         4.7    87510                8.7M   5000000  Free    0.0
3         4.5   215644                 25M  50000000  Free    0.0
4         4.3      967                2.8M    100000  Free    0.0
...       ...      ...                 ...       ...   ...    ...
10834     4.0        7                2.6M       500  Free    0.0
10836     4.5       38                 53M      5000  Free    0.0
10837     5.0        4                3.6M       100  Free    0.0
10839     4.5      114  Varies with device      1000  Free    0.0
10840     4.5   398307                 19M  10000000  Free    0.0

      Content Rating                     Genres Last Updated  \
0           Everyone               Art & Design   2018-01-07
1           Everyone  Art & Design;Pretend Play   2018-01-15
2           Everyone               Art & Design   2018-08-01
3               Teen               Art & Design   2018-06-08
4           Everyone    Art & Design;Creativity   2018-06-20
...              ...                        ...          ...
10834       Everyone                  Education   2017-06-18
10836       Everyone                  Education   2017-07-25
10837       Everyone                  Education   2018-07-06
10839     Mature 17+          Books & Reference   2015-01-19
10840       Everyone                  Lifestyle   2018-07-25

              Current Ver         Android Ver      Primary_Genre
0                   1.0.0        4.0.3 and up       Art & Design
1                   2.0.0        4.0.3 and up       Art & Design
2                   1.2.4        4.0.3 and up       Art & Design
3      Varies with device          4.2 and up       Art & Design
4                     1.1          4.4 and up       Art & Design
...                   ...                 ...                ...
10834               1.0.0          4.1 and up          Education
10836                1.48          4.1 and up          Education
10837                 1.0          4.1 and up          Education
10839  Varies with device  Varies with device  Books & Reference
10840  Varies with device  Varies with device          Lifestyle

[8279 rows x 14 columns]

21.Filter apps with installs greater than 1,000,000

In [55]:
print(df.loc[df["Installs"] > 1000000, ["App", "Installs"]])

                                                     App  Installs
2      u launcher lite – free live cool themes, hide ...   5000000
3                                  sketch - draw & paint  50000000
12                        tattoo name on my photo editor  10000000
18                         flipaclip - cartoon animation   5000000
19                                          ibis paint x  10000000
...                                                  ...       ...
10740                                         photofunia  10000000
10781                               modern strike online  10000000
10784                                         big hunter  10000000
10826          frim: get new friends on local chat rooms   5000000
10840      ihoroscope - 2018 daily horoscope & astrology  10000000

[2566 rows x 2 columns]

22.Select apps belonging to multiple categories

In [59]:
categories = ["GAME", "FAMILY", "TOOLS"]
print(df.loc[df["Category"].isin(categories), ["App", "Category"]])

                                    App Category
1653                             roblox     GAME
1654                     subway surfers     GAME
1655                   candy crush saga     GAME
1656                          solitaire     GAME
1657                     bubble shooter     GAME
...                                 ...      ...
10820                   fr. daoud lamei   FAMILY
10827                fr agnel ambarnath   FAMILY
10834                     fr calculator   FAMILY
10836                  sya9a maroc - fr   FAMILY
10837  fr. mike schmitz audio teachings   FAMILY

[3526 rows x 2 columns]

23.Perform filtering using query syntax

In [60]:
query_filtered = df.query("Rating > 4.0 and Price == 0")
print(query_filtered)

                                                     App             Category  \
0         photo editor & candy camera & grid & scrapbook       ART AND DESIGN
2      u launcher lite – free live cool themes, hide ...       ART AND DESIGN
3                                  sketch - draw & paint       ART AND DESIGN
4                  pixel draw - number art coloring book       ART AND DESIGN
5                             paper flowers instructions       ART AND DESIGN
...                                                  ...                  ...
10833                                        chemin (fr)  BOOKS AND REFERENCE
10836                                   sya9a maroc - fr               FAMILY
10837                   fr. mike schmitz audio teachings               FAMILY
10839                      the scp foundation db fr nn5n  BOOKS AND REFERENCE
10840      ihoroscope - 2018 daily horoscope & astrology            LIFESTYLE

       Rating  Reviews                Size  Installs  Type  Price  \
0         4.1      159                 19M     10000  Free    0.0
2         4.7    87510                8.7M   5000000  Free    0.0
3         4.5   215644                 25M  50000000  Free    0.0
4         4.3      967                2.8M    100000  Free    0.0
5         4.4      167                5.6M     50000  Free    0.0
...       ...      ...                 ...       ...   ...    ...
10833     4.8       44                619k      1000  Free    0.0
10836     4.5       38                 53M      5000  Free    0.0
10837     5.0        4                3.6M       100  Free    0.0
10839     4.5      114  Varies with device      1000  Free    0.0
10840     4.5   398307                 19M  10000000  Free    0.0

      Content Rating                   Genres Last Updated  \
0           Everyone             Art & Design   2018-01-07
2           Everyone             Art & Design   2018-08-01
3               Teen             Art & Design   2018-06-08
4           Everyone  Art & Design;Creativity   2018-06-20
5           Everyone             Art & Design   2017-03-26
...              ...                      ...          ...
10833       Everyone        Books & Reference   2014-03-23
10836       Everyone                Education   2017-07-25
10837       Everyone                Education   2018-07-06
10839     Mature 17+        Books & Reference   2015-01-19
10840       Everyone                Lifestyle   2018-07-25

              Current Ver         Android Ver      Primary_Genre
0                   1.0.0        4.0.3 and up       Art & Design
2                   1.2.4        4.0.3 and up       Art & Design
3      Varies with device          4.2 and up       Art & Design
4                     1.1          4.4 and up       Art & Design
5                     1.0          2.3 and up       Art & Design
...                   ...                 ...                ...
10833                 0.8          2.2 and up  Books & Reference
10836                1.48          4.1 and up          Education
10837                 1.0          4.1 and up          Education
10839  Varies with device  Varies with device  Books & Reference
10840  Varies with device  Varies with device          Lifestyle

[5934 rows x 14 columns]

## 5. FEATURE ENGINEERING

24.Create a new column "Revenue" using installs and price

In [61]:
df["Revenue"] = df["Installs"] * df["Price"]
print(df[["App", "Installs", "Price", "Revenue"]].head())

                                                 App  Installs  Price  Revenue
0     photo editor & candy camera & grid & scrapbook     10000    0.0      0.0
1                                coloring book moana    500000    0.0      0.0
2  u launcher lite – free live cool themes, hide ...   5000000    0.0      0.0
3                              sketch - draw & paint  50000000    0.0      0.0
4              pixel draw - number art coloring book    100000    0.0      0.0

25.Categorize apps into rating groups (Low, Medium, High)

In [63]:
df["Rating_Group"] = pd.cut(
    df["Rating"], bins=[0, 3.0, 4.2, 5.0], labels=["Low", "Medium", "High"]
)
print(df[["App", "Rating", "Rating_Group"]].head())

                                                 App  Rating Rating_Group
0     photo editor & candy camera & grid & scrapbook     4.1       Medium
1                                coloring book moana     3.9       Medium
2  u launcher lite – free live cool themes, hide ...     4.7         High
3                              sketch - draw & paint     4.5         High
4              pixel draw - number art coloring book     4.3         High

26.Create a new column to flag high-install apps (>1M installs)

In [64]:
df["High Install"] = df["Installs"].apply(lambda x: 1 if x > 1000000 else 0)
print(df["High Install"])

0        0
1        0
2        1
3        1
4        0
        ..
10834    0
10836    0
10837    0
10839    0
10840    1
Name: High Install, Length: 8892, dtype: int64

27.Convert "Type" column into numeric values (Free=0, Paid=1)

In [65]:
df["Type to Numeric"] = df["Type"].map({"Free": 0, "Paid": 1})
print(df["Type to Numeric"].unique())

[0 1]

In [66]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Primary_Genre,Revenue,Rating_Group,High Install,Type to Numeric
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,Art & Design,0.0,Medium,0,0
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,Art & Design,0.0,Medium,0,0
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,Art & Design,0.0,High,1,0
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,Art & Design,0.0,High,1,0
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,Art & Design,0.0,High,0,0

### 6. SORTING & RANKING

28.Sort apps by number of installs in descending order

In [67]:
df = df.sort_values(by="Installs", ascending=False)
print(df[["App", "Installs"]])

                                                   App    Installs
3896                                    subway surfers  1000000000
4153                                          hangouts  1000000000
4150                                            google  1000000000
3904                                whatsapp messenger  1000000000
3816                                       google news  1000000000
...                                                ...         ...
2450                                   tablet reminder           5
2459   anatomy & physiology vocabulary exam review app           5
5917                                          ra ga ba           1
2454                               kba-ez health guide           1
10697                                          mu.f.o.           1

[8892 rows x 2 columns]

29.Identify top 10 apps based on number of reviews

In [68]:
Top_10_apps = df.nlargest(10, "Reviews")
print(Top_10_apps[["App", "Reviews"]])

                                           App   Reviews
2544                                  facebook  78158306
3943                                  facebook  78128208
336                         whatsapp messenger  69119316
3904                        whatsapp messenger  69109672
2604                                 instagram  66577446
2545                                 instagram  66577313
3909                                 instagram  66509917
382   messenger – text and video chat for free  56646578
335   messenger – text and video chat for free  56642847
1879                            clash of clans  44893888

30.Identify bottom 10 apps based on installs

In [70]:
bottom_10_installed = df.nsmallest(10, "Installs")
print(bottom_10_installed[["App", "Installs"]])

                       App  Installs
5917              ra ga ba         1
2454   kba-ez health guide         1
10697              mu.f.o.         1
6700      brick breaker br         5
7147             cb heroes         5
8146               cz-help         5
10562          fk atlantas         5
9218   eb cash collections         5
2484     clinic doctor ehr         5
7731               cq espm         5

31.Rank apps based on rating

In [71]:
df["Rating Rank"] = df["Rating"].rank(ascending=False, method="min")
print(df[["App", "Rating", "Rating Rank"]])

                                                   App  Rating  Rating Rank
3896                                    subway surfers     4.5       1839.0
4153                                          hangouts     4.0       6409.0
4150                                            google     4.4       2816.0
3904                                whatsapp messenger     4.4       2816.0
3816                                       google news     3.9       6948.0
...                                                ...     ...          ...
2450                                   tablet reminder     5.0          1.0
2459   anatomy & physiology vocabulary exam review app     5.0          1.0
5917                                          ra ga ba     5.0          1.0
2454                               kba-ez health guide     5.0          1.0
10697                                          mu.f.o.     5.0          1.0

[8892 rows x 3 columns]

## 7. GROUPBY & AGGREGATION

32.Calculate average rating for each category

In [72]:
avg_rating_per_cat = df.groupby("Category")["Rating"].mean()
print(avg_rating_per_cat)

Category
ART AND DESIGN         4.358065
AUTO AND VEHICLES      4.190411
BEAUTY                 4.278571
BOOKS AND REFERENCE    4.347458
BUSINESS               4.102593
COMICS                 4.155172
COMMUNICATION          4.151466
DATING                 3.971698
EDUCATION              4.375969
ENTERTAINMENT          4.136036
EVENTS                 4.435556
FAMILY                 4.191153
FINANCE                4.127445
FOOD AND DRINK         4.164151
GAME                   4.281285
HEALTH AND FITNESS     4.261450
HOUSE AND HOME         4.164706
LIBRARIES AND DEMO     4.178462
LIFESTYLE              4.096066
MAPS AND NAVIGATION    4.051613
MEDICAL                4.182450
NEWS AND MAGAZINES     4.128505
PARENTING              4.300000
PERSONALIZATION        4.333871
PHOTOGRAPHY            4.182895
PRODUCTIVITY           4.201796
SHOPPING               4.251485
SOCIAL                 4.254918
SPORTS                 4.225175
TOOLS                  4.047411
TRAVEL AND LOCAL       4.094146
VIDEO PLAYERS          4.063750
WEATHER                4.244000
Name: Rating, dtype: float64

33.Calculate total installs for each category

In [74]:
total_installs_per_cat = df.groupby("Category")["Installs"].sum()
print(total_installs_per_cat)

Category
ART AND DESIGN           124233100
AUTO AND VEHICLES         53129800
BEAUTY                    26916200
BOOKS AND REFERENCE     1916291655
BUSINESS                 863518120
COMICS                    56036100
COMMUNICATION          24152241530
DATING                   206522410
EDUCATION                533852000
ENTERTAINMENT           2455660000
EVENTS                    15949410
FAMILY                 10041130590
FINANCE                  770312400
FOOD AND DRINK           257777750
GAME                   31543862717
HEALTH AND FITNESS      1361006220
HOUSE AND HOME           125082000
LIBRARIES AND DEMO        62083000
LIFESTYLE                534741120
MAPS AND NAVIGATION      724267560
MEDICAL                   42162676
NEWS AND MAGAZINES      5393110650
PARENTING                 31116110
PERSONALIZATION         2074352930
PHOTOGRAPHY             9721243130
PRODUCTIVITY           12463070180
SHOPPING                2573331540
SOCIAL                 12513841475
SPORTS                  1528531465
TOOLS                  11450724500
TRAVEL AND LOCAL        6361859300
VIDEO PLAYERS           6221897200
WEATHER                  426096500
Name: Installs, dtype: int64

34.Count the number of apps in each category

In [75]:
app_count_per_cat = df["Category"].value_counts()
print(app_count_per_cat)

Category
FAMILY                 1718
GAME                   1074
TOOLS                   734
PRODUCTIVITY            334
FINANCE                 317
PERSONALIZATION         310
COMMUNICATION           307
LIFESTYLE               305
PHOTOGRAPHY             304
MEDICAL                 302
SPORTS                  286
BUSINESS                270
HEALTH AND FITNESS      262
SOCIAL                  244
NEWS AND MAGAZINES      214
TRAVEL AND LOCAL        205
SHOPPING                202
BOOKS AND REFERENCE     177
VIDEO PLAYERS           160
DATING                  159
EDUCATION               129
MAPS AND NAVIGATION     124
ENTERTAINMENT           111
FOOD AND DRINK          106
WEATHER                  75
AUTO AND VEHICLES        73
HOUSE AND HOME           68
LIBRARIES AND DEMO       65
ART AND DESIGN           62
COMICS                   58
PARENTING                50
EVENTS                   45
BEAUTY                   42
Name: count, dtype: int64

35.Perform multiple aggregations (mean rating, max installs) per category

In [76]:
result = df.groupby("Category").agg({"Rating": "mean", "Installs": "max"})
print(result)

                       Rating    Installs
Category
ART AND DESIGN       4.358065    50000000
AUTO AND VEHICLES    4.190411    10000000
BEAUTY               4.278571    10000000
BOOKS AND REFERENCE  4.347458  1000000000
BUSINESS             4.102593   100000000
COMICS               4.155172    10000000
COMMUNICATION        4.151466  1000000000
DATING               3.971698    10000000
EDUCATION            4.375969   100000000
ENTERTAINMENT        4.136036  1000000000
EVENTS               4.435556     5000000
FAMILY               4.191153  1000000000
FINANCE              4.127445   100000000
FOOD AND DRINK       4.164151    10000000
GAME                 4.281285  1000000000
HEALTH AND FITNESS   4.261450   500000000
HOUSE AND HOME       4.164706    10000000
LIBRARIES AND DEMO   4.178462    10000000
LIFESTYLE            4.096066   100000000
MAPS AND NAVIGATION  4.051613   100000000
MEDICAL              4.182450     5000000
NEWS AND MAGAZINES   4.128505  1000000000
PARENTING            4.300000    10000000
PERSONALIZATION      4.333871   100000000
PHOTOGRAPHY          4.182895  1000000000
PRODUCTIVITY         4.201796  1000000000
SHOPPING             4.251485   100000000
SOCIAL               4.254918  1000000000
SPORTS               4.225175   100000000
TOOLS                4.047411  1000000000
TRAVEL AND LOCAL     4.094146  1000000000
VIDEO PLAYERS        4.063750  1000000000
WEATHER              4.244000    50000000

In [77]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Primary_Genre,Revenue,Rating_Group,High Install,Type to Numeric,Rating Rank
3896,subway surfers,GAME,4.5,27711703,76M,1000000000,Free,0.00,Everyone 10+,Arcade,2018-07-12,1.90.0,4.1 and up,Arcade,0.00,High,1,0,1839.0
4153,hangouts,COMMUNICATION,4.0,3419464,Varies with device,1000000000,Free,0.00,Everyone,Communication,2018-07-21,Varies with device,Varies with device,Communication,0.00,Medium,1,0,6409.0
4150,google,TOOLS,4.4,8021623,Varies with device,1000000000,Free,0.00,Everyone,Tools,2018-08-03,Varies with device,Varies with device,Tools,0.00,High,1,0,2816.0
3904,whatsapp messenger,COMMUNICATION,4.4,69109672,Varies with device,1000000000,Free,0.00,Everyone,Communication,2018-08-03,Varies with device,Varies with device,Communication,0.00,High,1,0,2816.0
3816,google news,NEWS AND MAGAZINES,3.9,877643,13M,1000000000,Free,0.00,Teen,News & Magazines,2018-08-01,5.2.0,4.4 and up,News & Magazines,0.00,Medium,1,0,6948.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2450,tablet reminder,MEDICAL,5.0,4,2.5M,5,Free,0.00,Everyone,Medical,2018-08-03,1.0,4.1 and up,Medical,0.00,High,0,0,1.0
2459,anatomy & physiology vocabulary exam review app,MEDICAL,5.0,1,4.6M,5,Free,0.00,Everyone,Medical,2018-08-02,2.0,4.0 and up,Medical,0.00,High,0,0,1.0
5917,ra ga ba,GAME,5.0,2,20M,1,Paid,1.49,Everyone,Arcade,2017-02-08,1.0.4,2.3 and up,Arcade,1.49,High,0,1,1.0
2454,kba-ez health guide,MEDICAL,5.0,4,25M,1,Free,0.00,Everyone,Medical,2018-08-02,1.0.72,4.0.3 and up,Medical,0.00,High,0,0,1.0
10697,mu.f.o.,GAME,5.0,2,16M,1,Paid,0.99,Everyone,Arcade,2017-03-03,1.0,2.3 and up,Arcade,0.99,High,0,1,1.0

## 8. MERGE / JOIN / CONCAT

36.Split the dataset into multiple tables

In [78]:
apps_info = df[["App", "Category", "Rating"]].drop_duplicates(subset=["App"])
installs_info = df[["App", "Installs", "Reviews"]].drop_duplicates(subset=["App"])
pricing_info = df[["App", "Type", "Price", "Revenue"]].drop_duplicates(subset=["App"])
print(apps_info.head())
print(installs_info.head())
print(pricing_info.head())

                     App            Category  Rating
3896      subway surfers                GAME     4.5
4153            hangouts       COMMUNICATION     4.0
4150              google               TOOLS     4.4
3904  whatsapp messenger       COMMUNICATION     4.4
3816         google news  NEWS AND MAGAZINES     3.9
                     App    Installs   Reviews
3896      subway surfers  1000000000  27711703
4153            hangouts  1000000000   3419464
4150              google  1000000000   8021623
3904  whatsapp messenger  1000000000  69109672
3816         google news  1000000000    877643
                     App  Type  Price  Revenue
3896      subway surfers  Free    0.0      0.0
4153            hangouts  Free    0.0      0.0
4150              google  Free    0.0      0.0
3904  whatsapp messenger  Free    0.0      0.0
3816         google news  Free    0.0      0.0

37.Merge app details with installs data using a common column

In [80]:
merged_df = pd.merge(apps_info, installs_info, on="App")
print(merged_df.head())

                  App            Category  Rating    Installs   Reviews
0      subway surfers                GAME     4.5  1000000000  27711703
1            hangouts       COMMUNICATION     4.0  1000000000   3419464
2              google               TOOLS     4.4  1000000000   8021623
3  whatsapp messenger       COMMUNICATION     4.4  1000000000  69109672
4         google news  NEWS AND MAGAZINES     3.9  1000000000    877643

38.Perform an inner join and observe the result

In [81]:
inner_join = pd.merge(apps_info, installs_info, on="App", how="inner")
print(inner_join.head())

                  App            Category  Rating    Installs   Reviews
0      subway surfers                GAME     4.5  1000000000  27711703
1            hangouts       COMMUNICATION     4.0  1000000000   3419464
2              google               TOOLS     4.4  1000000000   8021623
3  whatsapp messenger       COMMUNICATION     4.4  1000000000  69109672
4         google news  NEWS AND MAGAZINES     3.9  1000000000    877643

39.Perform a left join and identify missing values created after the merge

In [83]:
left_merged = pd.merge(apps_info, pricing_info, on="App", how="left")
missing_after_left_join = left_merged.isnull().sum()
print(left_merged.head())

                  App            Category  Rating  Type  Price  Revenue
0      subway surfers                GAME     4.5  Free    0.0      0.0
1            hangouts       COMMUNICATION     4.0  Free    0.0      0.0
2              google               TOOLS     4.4  Free    0.0      0.0
3  whatsapp messenger       COMMUNICATION     4.4  Free    0.0      0.0
4         google news  NEWS AND MAGAZINES     3.9  Free    0.0      0.0

40.Combine two DataFrames vertically to simulate adding new data

In [85]:
df_part1 = df.iloc[:5000]
df_part2 = df.iloc[5000:]
combined_data = pd.concat([df_part1, df_part2], axis=0)
print(combined_data)

                                                   App            Category  \
3896                                    subway surfers                GAME
4153                                          hangouts       COMMUNICATION
4150                                            google               TOOLS
3904                                whatsapp messenger       COMMUNICATION
3816                                       google news  NEWS AND MAGAZINES
...                                                ...                 ...
2450                                   tablet reminder             MEDICAL
2459   anatomy & physiology vocabulary exam review app             MEDICAL
5917                                          ra ga ba                GAME
2454                               kba-ez health guide             MEDICAL
10697                                          mu.f.o.                GAME

       Rating   Reviews                Size    Installs  Type  Price  \
3896      4.5  27711703                 76M  1000000000  Free   0.00
4153      4.0   3419464  Varies with device  1000000000  Free   0.00
4150      4.4   8021623  Varies with device  1000000000  Free   0.00
3904      4.4  69109672  Varies with device  1000000000  Free   0.00
3816      3.9    877643                 13M  1000000000  Free   0.00
...       ...       ...                 ...         ...   ...    ...
2450      5.0         4                2.5M           5  Free   0.00
2459      5.0         1                4.6M           5  Free   0.00
5917      5.0         2                 20M           1  Paid   1.49
2454      5.0         4                 25M           1  Free   0.00
10697     5.0         2                 16M           1  Paid   0.99

      Content Rating            Genres Last Updated         Current Ver  \
3896    Everyone 10+            Arcade   2018-07-12              1.90.0
4153        Everyone     Communication   2018-07-21  Varies with device
4150        Everyone             Tools   2018-08-03  Varies with device
3904        Everyone     Communication   2018-08-03  Varies with device
3816            Teen  News & Magazines   2018-08-01               5.2.0
...              ...               ...          ...                 ...
2450        Everyone           Medical   2018-08-03                 1.0
2459        Everyone           Medical   2018-08-02                 2.0
5917        Everyone            Arcade   2017-02-08               1.0.4
2454        Everyone           Medical   2018-08-02              1.0.72
10697       Everyone            Arcade   2017-03-03                 1.0

              Android Ver     Primary_Genre  Revenue Rating_Group  \
3896           4.1 and up            Arcade     0.00         High
4153   Varies with device     Communication     0.00       Medium
4150   Varies with device             Tools     0.00         High
3904   Varies with device     Communication     0.00         High
3816           4.4 and up  News & Magazines     0.00       Medium
...                   ...               ...      ...          ...
2450           4.1 and up           Medical     0.00         High
2459           4.0 and up           Medical     0.00         High
5917           2.3 and up            Arcade     1.49         High
2454         4.0.3 and up           Medical     0.00         High
10697          2.3 and up            Arcade     0.99         High

       High Install  Type to Numeric  Rating Rank
3896              1                0       1839.0
4153              1                0       6409.0
4150              1                0       2816.0
3904              1                0       2816.0
3816              1                0       6948.0
...             ...              ...          ...
2450              0                0          1.0
2459              0                0          1.0
5917              0                1          1.0
2454              0                0          1.0
10697             0                1          1.0

[8892 rows x 19 columns]