In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("nba.csv")
print(df)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0
457                NaN        NaN

[458 rows x 9 columns]

In [3]:
df.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='str')

In [4]:
df["Name"]

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: str

In [5]:
df1 = df[["Name","Salary"]]
df1

              Name     Salary
0    Avery Bradley  7730337.0
1      Jae Crowder  6796117.0
2     John Holland        NaN
3      R.J. Hunter  1148640.0
4    Jonas Jerebko  5000000.0
..             ...        ...
453   Shelvin Mack  2433333.0
454      Raul Neto   900000.0
455   Tibor Pleiss  2900000.0
456    Jeff Withey   947276.0
457            NaN        NaN

[458 rows x 2 columns]

In [24]:
df["Experience"] = 2

In [25]:
df["Salary_after_bonus"] = df["Salary"] * 1.10
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experiance,Salary_aftter_bonus,Salary_after_bonus,Experience
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2,8503370.7,8503370.7,2
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2,7475728.7,7475728.7,2
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2,NaN,NaN,2
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2,1263504.0,1263504.0,2
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2,5500000.0,5500000.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,2,2676666.3,2676666.3,2
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,2,990000.0,990000.0,2
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,2,3190000.0,3190000.0,2
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,2,1042003.6,1042003.6,2
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,2

In [26]:
df=df.drop("Salary_aftter_bonus", axis=1)

In [27]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experiance,Salary_after_bonus,Experience
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2,8503370.7,2
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2,7475728.7,2
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2,NaN,2
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2,1263504.0,2
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2,5500000.0,2

In [28]:
df2=df.drop("Experience", axis=1)
df2

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experiance,Salary_after_bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2,8503370.7
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2,7475728.7
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2,1263504.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2,5500000.0
...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,2,2676666.3
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,2,990000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,2,3190000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,2,1042003.6
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN

In [29]:
#df.drop("Experience", axis=1,inplace=True)
#df=df.drop("Experience", axis=1)

In [30]:
df3=df2.drop("Salary_after_bonus", axis=1)
df3

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experiance
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,2
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,2
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,2
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,2
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2

In [31]:
new_row = {
    "Name": "Emma",
    "Team":"Boston Celtics",
    "Number":99.0,
    "Position": "SG",
    "Age":25,
    "Height":"6-10",
    "Weight":231.0,
    "College":"Butler",
    
    "Salary":900000
}

new_df = pd.DataFrame([new_row])

print(new_df)
print("*****************************")
print()
#df4 = pd.concat([df3, new_df])
df4 = pd.concat([df3, new_df], ignore_index=True)
print(df4)

   Name            Team  Number Position  Age Height  Weight College  Salary
0  Emma  Boston Celtics    99.0       SG   25   6-10   231.0  Butler  900000
*****************************

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN
458           Emma  Boston Celtics    99.0       SG  25.0   6-10   231.0

               College     Salary  Experiance
0                Texas  7730337.0         2.0
1            Marquette  6796117.0         2.0
2    Boston University        NaN         2.0
3        Georgia State  1148640.0         2.0
4                  NaN  5000000.0         2.0
..                 ...        ...         ...
454                NaN   900000.0         2.0
455                NaN  2900000.0         2.0
456             Kansas   947276.0         2.0
457                NaN        NaN         2.0
458             Butler   900000.0         NaN

[459 rows x 10 columns]

In [32]:
df4.drop(2, inplace=True)

print(df4)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
5     Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
..             ...             ...     ...      ...   ...    ...     ...
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN
458           Emma  Boston Celtics    99.0       SG  25.0   6-10   231.0

           College      Salary  Experiance
0            Texas   7730337.0         2.0
1        Marquette   6796117.0         2.0
3    Georgia State   1148640.0         2.0
4              NaN   5000000.0         2.0
5              NaN  12000000.0         2.0
..             ...         ...         ...
454            NaN    900000.0         2.0
455            NaN   2900000.0         2.0
456         Kansas    947276.0         2.0
457            NaN         NaN         2.0
458         Butler    900000.0         NaN

[458 rows x 10 columns]

In [33]:
df4.drop(457, inplace=True)

print(df4)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
5     Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
458           Emma  Boston Celtics    99.0       SG  25.0   6-10   231.0

           College      Salary  Experiance
0            Texas   7730337.0         2.0
1        Marquette   6796117.0         2.0
3    Georgia State   1148640.0         2.0
4              NaN   5000000.0         2.0
5              NaN  12000000.0         2.0
..             ...         ...         ...
453         Butler   2433333.0         2.0
454            NaN    900000.0         2.0
455            NaN   2900000.0         2.0
456         Kansas    947276.0         2.0
458         Butler    900000.0         NaN

[457 rows x 10 columns]

In [34]:
df4.drop(1, inplace=True)

print(df4)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
5     Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
6    Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
458           Emma  Boston Celtics    99.0       SG  25.0   6-10   231.0

           College      Salary  Experiance
0            Texas   7730337.0         2.0
3    Georgia State   1148640.0         2.0
4              NaN   5000000.0         2.0
5              NaN  12000000.0         2.0
6              LSU   1170960.0         2.0
..             ...         ...         ...
453         Butler   2433333.0         2.0
454            NaN    900000.0         2.0
455            NaN   2900000.0         2.0
456         Kansas    947276.0         2.0
458         Butler    900000.0         NaN

[456 rows x 10 columns]

In [35]:
df4.reset_index(drop=True)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experiance
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2.0
1,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2.0
2,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2.0
3,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0,2.0
4,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0,2.0
...,...,...,...,...,...,...,...,...,...,...
451,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,2.0
452,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,2.0
453,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,2.0
454,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,2.0
455,Emma,Boston Celtics,99.0,SG,25.0,6-10,231.0,Butler,900000.0,NaN

In [36]:
# df4.drop(1, inplace=True)
# df4.reset_index(drop=True)

In [37]:
#df4.drop(1, inplace=True).reset_index(drop=True

loc[] and iloc[] in Pandas

In [38]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [40000, 50000, 45000, 52000, 48000]
}
df = pd.DataFrame(data)
print(df)

      Name  Age Department  Salary
0    Alice   23         HR   40000
1      Bob   25         IT   50000
2  Charlie   22    Finance   45000
3    David   24         IT   52000
4     Emma   26  Marketing   48000

In [39]:
df.loc[[2]]

      Name  Age Department  Salary
2  Charlie   22    Finance   45000

In [40]:
df.loc[[1,3]]

    Name  Age Department  Salary
1    Bob   25         IT   50000
3  David   24         IT   52000

In [41]:
df.loc[2,"Name"]

'Charlie'

In [43]:
df.loc[2, ["Name","Salary"]]

Name      Charlie
Salary      45000
Name: 2, dtype: object

In [44]:
df.loc[[1,3], ["Name","Department"]]

    Name Department
1    Bob         IT
3  David         IT

In [45]:
df.loc[1:3]

      Name  Age Department  Salary
1      Bob   25         IT   50000
2  Charlie   22    Finance   45000
3    David   24         IT   52000

In [46]:
df.loc[df["Salary"] > 45000]

    Name  Age Department  Salary
1    Bob   25         IT   50000
3  David   24         IT   52000
4   Emma   26  Marketing   48000

In [47]:
df.loc[df["Salary"] > 45000, ["Name","Salary"]]

    Name  Salary
1    Bob   50000
3  David   52000
4   Emma   48000

In [48]:
df.loc[2,"Salary"] = 47000
df

      Name  Age Department  Salary
0    Alice   23         HR   40000
1      Bob   25         IT   50000
2  Charlie   22    Finance   47000
3    David   24         IT   52000
4     Emma   26  Marketing   48000

In [49]:
# data = {
#     "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
#     "Age": [23, 25, 22, 24, 26],
#     "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
#     "Salary": [40000, 50000, 45000, 52000, 48000]
# }

# df = pd.DataFrame(data,index=[1,2,3,4,5])



# print(df)

      Name  Age Department  Salary
1    Alice   23         HR   40000
2      Bob   25         IT   50000
3  Charlie   22    Finance   45000
4    David   24         IT   52000
5     Emma   26  Marketing   48000

In [50]:
df.loc[1]

Name          Alice
Age              23
Department       HR
Salary        40000
Name: 1, dtype: object

In [51]:
df.iloc[1]

Name            Bob
Age              25
Department       IT
Salary        50000
Name: 2, dtype: object

In [52]:
df.loc[1:4]

      Name  Age Department  Salary
1    Alice   23         HR   40000
2      Bob   25         IT   50000
3  Charlie   22    Finance   45000
4    David   24         IT   52000

In [53]:
df.iloc[1:4]

      Name  Age Department  Salary
2      Bob   25         IT   50000
3  Charlie   22    Finance   45000
4    David   24         IT   52000

In [54]:
df.iloc[2]

Name          Charlie
Age                22
Department    Finance
Salary          45000
Name: 3, dtype: object

In [55]:
df.iloc[[1,3]]

    Name  Age Department  Salary
2    Bob   25         IT   50000
4  David   24         IT   52000

In [58]:
df.iloc[2,1]

np.int64(22)

In [59]:
df.iloc[2,[0,3]]

Name      Charlie
Salary      45000
Name: 3, dtype: object

In [62]:
df.iloc[[1,3],[0,2]]

    Name Department
2    Bob         IT
4  David         IT

In [63]:
df.iloc[1:4]

      Name  Age Department  Salary
2      Bob   25         IT   50000
3  Charlie   22    Finance   45000
4    David   24         IT   52000

In [64]:
df.iloc[:,1:3]

   Age Department
1   23         HR
2   25         IT
3   22    Finance
4   24         IT
5   26  Marketing

In [65]:
df.iloc[:,1]

1    23
2    25
3    22
4    24
5    26
Name: Age, dtype: int64

In [66]:
#Task:
#create a dataframe from this dictionary
#check shape and info
#display first 2 rows and last 2 rows
#check statitical summary
#Sort based on salary
#create a new column City with constant value 'NewJersy'
#create a calculated column revised salary = salary+2000
#create a new row with another persons details for IT department
#check value counts for Department
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [40000, 50000, 45000, 52000, 48000]
}

In [67]:
df = pd.DataFrame(data)
df

      Name  Age Department  Salary
0    Alice   23         HR   40000
1      Bob   25         IT   50000
2  Charlie   22    Finance   45000
3    David   24         IT   52000
4     Emma   26  Marketing   48000

In [68]:
df.shape

(5, 4)

In [69]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      int64
 2   Department  5 non-null      str
 3   Salary      5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 338.0 bytes

In [70]:
df.head(2)

    Name  Age Department  Salary
0  Alice   23         HR   40000
1    Bob   25         IT   50000

In [71]:
df.tail(2)

    Name  Age Department  Salary
3  David   24         IT   52000
4   Emma   26  Marketing   48000

In [72]:
data = {
    "Name": ["A", "B", "C", "D", "E", "F"],
    "Age": [23, 45, 31, 22, 35, 28],
    "Salary": [40000, 80000, 50000, 30000, 90000, 60000],
    "Department": ["HR", "IT", "Finance", "HR", "IT", "Finance"]
}

df = pd.DataFrame(data)

# custom index
df.index = ["emp1", "emp2", "emp3", "emp4", "emp5", "emp6"]

print(df)

     Name  Age  Salary Department
emp1    A   23   40000         HR
emp2    B   45   80000         IT
emp3    C   31   50000    Finance
emp4    D   22   30000         HR
emp5    E   35   90000         IT
emp6    F   28   60000    Finance

In [73]:
df.iloc[0:3]

     Name  Age  Salary Department
emp1    A   23   40000         HR
emp2    B   45   80000         IT
emp3    C   31   50000    Finance

In [74]:
df.iloc[2:5,1:3]

      Age  Salary
emp3   31   50000
emp4   22   30000
emp5   35   90000

In [75]:
df.iloc[:,0:2]

     Name  Age
emp1    A   23
emp2    B   45
emp3    C   31
emp4    D   22
emp5    E   35
emp6    F   28

In [76]:
df.iloc[::2]

     Name  Age  Salary Department
emp1    A   23   40000         HR
emp3    C   31   50000    Finance
emp5    E   35   90000         IT

In [77]:
df.iloc[::-1]

     Name  Age  Salary Department
emp6    F   28   60000    Finance
emp5    E   35   90000         IT
emp4    D   22   30000         HR
emp3    C   31   50000    Finance
emp2    B   45   80000         IT
emp1    A   23   40000         HR

In [78]:
df.loc["emp1":"emp3"]

     Name  Age  Salary Department
emp1    A   23   40000         HR
emp2    B   45   80000         IT
emp3    C   31   50000    Finance

In [80]:
df.loc["emp2":"emp5","Name":"Salary"]

     Name  Age  Salary
emp2    B   45   80000
emp3    C   31   50000
emp4    D   22   30000
emp5    E   35   90000

In [81]:
df.loc[:,"Age":"Department"]

      Age  Salary Department
emp1   23   40000         HR
emp2   45   80000         IT
emp3   31   50000    Finance
emp4   22   30000         HR
emp5   35   90000         IT
emp6   28   60000    Finance

In [82]:
df.loc["emp3":,:]

     Name  Age  Salary Department
emp3    C   31   50000    Finance
emp4    D   22   30000         HR
emp5    E   35   90000         IT
emp6    F   28   60000    Finance

In [83]:
df.loc["emp2":"emp4","Salary"]

emp2    80000
emp3    50000
emp4    30000
Name: Salary, dtype: int64

In [88]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [40000, 50000, 45000, 52000, 48000]
}

df = pd.DataFrame(data,index =[ x for x in 'ABCDE'])



print(df)

      Name  Age Department  Salary
A    Alice   23         HR   40000
B      Bob   25         IT   50000
C  Charlie   22    Finance   45000
D    David   24         IT   52000
E     Emma   26  Marketing   48000