In [1]:
import pandas as pd

data = {
    "Department": ["HR", "IT", "IT", "HR", "Finance", "IT", "Finance"],
    "Employee": ["A", "B", "C", "D", "E", "F", "G"],
    "Salary": [40000, 60000, 65000, 45000, 70000, 62000, 72000],
    "Experience": [2, 5, 6, 3, 8, 4, 9],
    "City":["Bangalore","Chennai","Kochi","Kochi","Chennai","Kochi","Mumbai"]
}

df = pd.DataFrame(data)
df

  Department Employee  Salary  Experience       City
0         HR        A   40000           2  Bangalore
1         IT        B   60000           5    Chennai
2         IT        C   65000           6      Kochi
3         HR        D   45000           3      Kochi
4    Finance        E   70000           8    Chennai
5         IT        F   62000           4      Kochi
6    Finance        G   72000           9     Mumbai

In [2]:
df.groupby("Department")["Salary"].mean()

Department
Finance    71000.000000
HR         42500.000000
IT         62333.333333
Name: Salary, dtype: float64

In [3]:
df.groupby("Department")["Salary"].sum()

Department
Finance    142000
HR          85000
IT         187000
Name: Salary, dtype: int64

In [4]:
df.groupby("Department")["Salary"].max()

Department
Finance    72000
HR         45000
IT         65000
Name: Salary, dtype: int64

In [5]:
df.groupby("Department")["Salary"].min()

Department
Finance    70000
HR         40000
IT         60000
Name: Salary, dtype: int64

In [8]:
df.groupby("Department")['Employee'].count()

Department
Finance    2
HR         2
IT         3
Name: Employee, dtype: int64

In [9]:
df.groupby('City')['Employee'].count()

City
Bangalore    1
Chennai      2
Kochi        3
Mumbai       1
Name: Employee, dtype: int64

In [10]:
df.groupby("Department")["Salary"].agg(["mean","max","min"])

                    mean    max    min
Department
Finance     71000.000000  72000  70000
HR          42500.000000  45000  40000
IT          62333.333333  65000  60000

In [12]:
df.groupby('Department')['Experience'].agg(['max','min'])

            max  min
Department
Finance       9    8
HR            3    2
IT            6    4

In [13]:
df.groupby("Department").agg({
    "Salary": ["mean", "max"],
    "Experience": ["min", "max"]
})

                  Salary        Experience
                    mean    max        min max
Department
Finance     71000.000000  72000          8   9
HR          42500.000000  45000          2   3
IT          62333.333333  65000          4   6

In [17]:
import pandas as pd

df = pd.DataFrame({
    "Numbers": [1, 2, 3, 4, 5, 6]
})

even_numbers = df["Numbers"].apply(lambda x: x if x % 2 == 0 else None).dropna().tolist()

print(even_numbers)

[2.0, 4.0, 6.0]

In [20]:
import pandas as pd

data = {
    "Department": ["HR", "IT", "IT", "HR", "Finance", "IT", "Finance"],
    "Employee": ["A", "B", "C", "D", "E", "F", "G"],
    "Salary": [40000, 60000, 65000, 45000, 70000, 62000, 72000],
    "Experience": [2, 5, 6, 3, 8, 4, 9],
    "City":["Bangalore","Chennai","Kochi","Kochi","Chennai","Kochi","Mumbai"]
}

df = pd.DataFrame(data)
df

  Department Employee  Salary  Experience       City
0         HR        A   40000           2  Bangalore
1         IT        B   60000           5    Chennai
2         IT        C   65000           6      Kochi
3         HR        D   45000           3      Kochi
4    Finance        E   70000           8    Chennai
5         IT        F   62000           4      Kochi
6    Finance        G   72000           9     Mumbai

In [21]:
df.groupby("Department").agg(
    Average_Salary=("Salary","mean"),
    Maximum_Salary=("Salary","max"),
Maximum_Experience=("Experience","max"),
Minimum_Experience=("Experience","min"),
)

,Average_Salary,Maximum_Salary,Maximum_Experience,Minimum_Experience
Department,,,,
Finance,71000.000000,72000,9,8
HR,42500.000000,45000,3,2
IT,62333.333333,65000,6,4

In [22]:
df.groupby("Department").agg(
    avg_salary=("Salary", "mean"),
    max_exp=("Experience", "max"),
    total_emp=("Employee", "count")
)

              avg_salary  max_exp  total_emp
Department
Finance     71000.000000        9          2
HR          42500.000000        3          2
IT          62333.333333        6          3

In [24]:
data = {
    "Department": ["HR", "IT", "IT", "HR", "Finance", "IT", "Finance"],
    "Employee": ["A", "B", "C", "D", "E", "F", "G"],
    "Salary": [40000, 60000, 65000, 45000, 70000, 62000, 72000],
    "Experience": [2, 5, 6, 2, 8, 4, 8],
    "City":["Bangalore","Chennai","Kochi","Kochi","Chennai","Kochi","Mumbai"]
}

df1 = pd.DataFrame(data)
df1

  Department Employee  Salary  Experience       City
0         HR        A   40000           2  Bangalore
1         IT        B   60000           5    Chennai
2         IT        C   65000           6      Kochi
3         HR        D   45000           2      Kochi
4    Finance        E   70000           8    Chennai
5         IT        F   62000           4      Kochi
6    Finance        G   72000           8     Mumbai

In [25]:
df1.groupby(["Department", "Experience"])["Salary"].mean().reset_index()

  Department  Experience   Salary
0    Finance           8  71000.0
1         HR           2  42500.0
2         IT           4  62000.0
3         IT           5  60000.0
4         IT           6  65000.0

In [26]:
df["Dept_Avg_Salary"] = df.groupby("Department")["Salary"].transform("mean")
df

  Department Employee  Salary  Experience       City  Dept_Avg_Salary
0         HR        A   40000           2  Bangalore     42500.000000
1         IT        B   60000           5    Chennai     62333.333333
2         IT        C   65000           6      Kochi     62333.333333
3         HR        D   45000           3      Kochi     42500.000000
4    Finance        E   70000           8    Chennai     71000.000000
5         IT        F   62000           4      Kochi     62333.333333
6    Finance        G   72000           9     Mumbai     71000.000000

In [28]:
df1 = df.groupby("Department")["Salary"].mean()
df1

Department
Finance    71000.000000
HR         42500.000000
IT         62333.333333
Name: Salary, dtype: float64

In [29]:
 df2 = df.groupby("Department")["Salary"].count()
 df2

Department
Finance    2
HR         2
IT         3
Name: Salary, dtype: int64

In [30]:
df3 = df.groupby("Department")["Salary"].max()
df3

Department
Finance    72000
HR         45000
IT         65000
Name: Salary, dtype: int64

In [34]:
df["highest_Avg_Salary"] = df.groupby("Department")["Salary"].transform("mean").max()
df

,Department,Employee,Salary,Experience,City,Dept_Avg_Salary,highest_Avg_Salary
0,HR,A,40000,2,Bangalore,42500.000000,71000.0
1,IT,B,60000,5,Chennai,62333.333333,71000.0
2,IT,C,65000,6,Kochi,62333.333333,71000.0
3,HR,D,45000,3,Kochi,42500.000000,71000.0
4,Finance,E,70000,8,Chennai,71000.000000,71000.0
5,IT,F,62000,4,Kochi,62333.333333,71000.0
6,Finance,G,72000,9,Mumbai,71000.000000,71000.0

In [36]:
df["Salary_Diff"] = df["Salary"] - df["Dept_Avg_Salary"]
df

,Department,Employee,Salary,Experience,City,Dept_Avg_Salary,highest_Avg_Salary,Salary_Diff
0,HR,A,40000,2,Bangalore,42500.000000,71000.0,-2500.000000
1,IT,B,60000,5,Chennai,62333.333333,71000.0,-2333.333333
2,IT,C,65000,6,Kochi,62333.333333,71000.0,2666.666667
3,HR,D,45000,3,Kochi,42500.000000,71000.0,2500.000000
4,Finance,E,70000,8,Chennai,71000.000000,71000.0,-1000.000000
5,IT,F,62000,4,Kochi,62333.333333,71000.0,-333.333333
6,Finance,G,72000,9,Mumbai,71000.000000,71000.0,1000.000000

In [40]:
df("Top Employee") = df.groupby("Department").transform("mean").max()

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (973077970.py, line 1)